// Mothership: the mothership beams energy down, so energy never drops below 45 while CI passes.
export default {
  id: 'alien',
  trait: 'mothership',
  home: 'desert',
  modifiers: { ciEnergyFloor: 45 },
  food: 'kibble',
  move: 'beam',
  palette: {
    o: '#1c3315', b: '#a6e04f', l: '#dcf7a8', s: '#72b33a', y: '#ffe14d', Y: '#fffbd0',
    m: '#e3e8f0', M: '#9aa5b8',
  },
  shinyKeep: ['y', 'Y', 'm', 'M'],
  grid: [
    '.oo..........oo.',
    'oYyo........oYyo',
    'oyyo........oyyo',
    '.oo.o.oooo.o.oo.',
    '....oollbboo....',
    '..oolbbbbbbboo..',
    '.olbbbbbbbbbbbo.',
    'olbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbso',
    '.obbbbbbbbbbbso.',
    '..osbbbbbbbbso..',
    '...osbbbbbbso...',
    '..oMmmmmmmyyMo..',
    '...oooooooooo...',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[2, 10], [12, 10]],
  hat: [8, 3],
};
