// Mothership: the mothership beams energy down, so energy never drops below 45 while CI passes.
export default {
  id: 'alien',
  trait: 'mothership',
  home: 'desert',
  modifiers: { ciEnergyFloor: 45 },
  food: 'kibble',
  move: 'beam',
  palette: {
    o: '#1c3315', b: '#a6e04f', l: '#dcf7a8', s: '#72b33a', y: '#ffe14d', Y: '#fffbd0',
    m: '#e3e8f0', M: '#9aa5b8', r: '#ff4d6d',
  },
  shinyKeep: ['y', 'Y', 'm', 'M', 'r'],
  grid: [
    '.oo..........oo.',
    'oYyo........oyYo',
    'oyyo........oyyo',
    '.oo.o......o.oo.',
    '.....oooooo.....',
    '...oollbbbboo...',
    '..ollbbbbbbbbo..',
    '.olbbbbbbbbbbbo.',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbso',
    '.osbbbbbbbbbbso.',
    '..omsbbbbbbsMo..',
    '.ommmmmmmmmyyMo.',
    '..oooooooooooo..',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[2, 10], [12, 10]],
  hat: [8, 4],
};
