// Regenerate: an axolotl regrows what it loses, so failing CI hurts it 40% less.
export default {
  id: 'axolotl',
  trait: 'regenerate',
  home: 'pond',
  modifiers: { ciPenalty: 0.6 },
  food: 'kibble',
  move: 'float',
  palette: {
    o: '#4a1630', b: '#ffbdd0', l: '#ffe3ec', s: '#f394b2', g: '#ea5a9e', G: '#b8306f', c: '#fff3e6',
  },
  grid: [
    '...Gg......gG...',
    'GG.Gg......gG.GG',
    '.Gg.Gg....gG.gG.',
    '.GgG.oooooo.GgG.',
    'G.GgoollbboogG.G',
    'GgGollbbbbbboGgG',
    '.GgolbbbbbbbogG.',
    '..olbbbbbbbbbo..',
    '.obbbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '..obbbbbbbbbbo..',
    '..osbccccccbso..',
    '..osbccccccbso..',
    '.obosccccccsobo.',
    '.oo.oooooooo.oo.',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 9],
  cheeks: [[2, 9], [12, 9]],
  hat: [8, 3],
};
