// Dream Eater: snacks on bad dreams, so its energy never drops below 30.
export default {
  id: 'baku',
  trait: 'dreamEater',
  home: 'meadow',
  modifiers: { energyFloor: 30 },
  food: 'kibble',
  move: 'doze',
  palette: {
    o: '#33244f', b: '#c7b3ee', l: '#e6dcfb', s: '#a08ad6', c: '#e6dbfb', p: '#ffb3d1', y: '#ffe27a',
  },
  shinyKeep: ['y'],
  grid: [
    '.oo..oooooo..oo.',
    'oppoolbyybbooppo',
    'opollbybbbbbsopo',
    '.olbbbbyybbbbso.',
    'olbbbbbbbbbbbbso',
    'obbbbbbbbbbbbbso',
    'obbbbbbbbbbbbbso',
    'obbbbsbbbbsbbbso',
    'obbbbsbbbbsbbbso',
    '.osbbsbbbbsbbso.',
    '.oooosbbbbsoooo.',
    '.obbo.obso.obbo.',
    '.osso.obso.osso.',
    '.oooo.obbsooooo.',
    '.......oooo.....',
    '................',
  ],
  eyes: [[4, 5], [10, 5]],
  mouth: [6, 7],
  cheeks: [[2, 7], [12, 7]],
  hat: [8, 0],
};
