// Drought-proof: thrives on neglect. Hunger builds 4× slower, perfect for finished projects.
export default {
  id: 'cactus',
  trait: 'drought',
  modifiers: { hungerRate: 0.25 },
  food: 'water',
  palette: {
    o: '#1d3b23', b: '#58b368', l: '#9be3a3', s: '#3c8a4b', d: '#e4f7d2',
    p: '#e8875a', P: '#b8553a',
  },
  shinyKeep: ['p', 'P'],
  grid: [
    '....oooooooo....',
    '...obbdbbdbbo...',
    '...oblbbbbbbo...',
    'oooobbbbbbbboooo',
    'obooblbbbbbboobo',
    'oboobbbbbbbboobo',
    'obbbbbbbbbbbbbbo',
    'oooobbbbbbbboooo',
    '...obdbbbbbbo...',
    '...obbbbbbdbo...',
    '..oooooooooooo..',
    '..oppppppppppo..',
    '..oooooooooooo..',
    '...oPPPPPPPPo...',
    '...oPPPPPPPPo...',
    '....oooooooo....',
  ],
  eyes: [[4, 4], [10, 4]],
  mouth: [6, 7],
  cheeks: [[4, 6], [10, 6]],
  hat: [8, 0],
};
