// Independent: ignored issues hurt a cat's joy only half as much.
export default {
  id: 'cat',
  trait: 'independent',
  modifiers: { issuePenalty: 0.5 },
  food: 'kibble',
  palette: { o: '#3b2416', b: '#f4a259', l: '#ffd2a1', s: '#d9822b', w: '#fff4e6', p: '#ff9eb5' },
  grid: [
    '................',
    '.oo..........oo.',
    '.obo........obo.',
    '.opbo......obpo.',
    '.obbboooooobbbo.',
    '.obbbbsbbsbbbbo.',
    'obbbbbsbbsbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    '.obbbbbbbbbbbbo.',
    '..obbwwwwwwbbo..',
    '..obwwwwwwwwbo..',
    '..oooooooooooo..',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[2, 10], [12, 10]],
  hat: [8, 4],
};
