// Molting: crabs grow a new shell with every release, a joy boost that lasts two weeks.
export default {
  id: 'crab',
  trait: 'molting',
  home: 'beach',
  modifiers: { releaseJoy: 15 },
  food: 'kibble',
  palette: { o: '#3a1010', b: '#ff6b5b', l: '#ffa596', s: '#d94c3d' },
  grid: [
    '................',
    '.ooo........ooo.',
    'olbbo......olbbo',
    'ob.oo......oo.bo',
    'obbbo......obbbo',
    '.obo.oooooo.obo.',
    '..obobbbbbbobo..',
    '...ollbbbbbbo...',
    '..obbbbbbbbbbo..',
    '.obbbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.osbbbbbbbbbbso.',
    '..ossbbbbbbsso..',
    '..oooooooooooo..',
    '.o.o.o....o.o.o.',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[2, 10], [12, 10]],
  hat: [8, 5],
};
