// Seven Falls: fall seven times, stand up eight. Failing CI can't push its health below 45.
export default {
  id: 'daruma',
  trait: 'sevenFalls',
  home: 'meadow',
  modifiers: { healthFloor: 45 },
  food: 'kibble',
  move: 'wobble',
  palette: {
    o: '#3a0d12', b: '#e23a3f', l: '#ff8a7a', s: '#b0212d', w: '#fbefdc', W: '#ecd3b6', n: '#2b1416',
    g: '#6e4a44', y: '#ffcf3a', Y: '#d9921a',
  },
  shinyKeep: ['w', 'W', 'n', 'g', 'y', 'Y'],
  grid: [
    '................',
    '......oooo......',
    '....oollbboo....',
    '...olbbbbbbbo...',
    '..olnnnwwnnnso..',
    '.olwwwwwwwwwwso.',
    'olbwwwwwwwwwwbso',
    'obbwwwwwwwwwwbso',
    'obbwwwwwwwwwwbso',
    'obbwwwwwwwwwwbso',
    'obbwwwwwwwwwwbso',
    'obbbwgwwwwgwbbso',
    'obbybWggggWbybso',
    '.osbyybYYbyybso.',
    '..oooooooooooo..',
    '................',
  ],
  eyes: [[4, 6], [10, 6]],
  mouth: [6, 9],
  cheeks: [[3, 8], [11, 8]],
  hat: [8, 1],
};
