// Debugger: a rubber duck helps you debug, so failing CI hurts it less.
export default {
  id: 'duck',
  trait: 'debugger',
  home: 'pond',
  modifiers: { ciPenalty: 0.65 },
  food: 'kibble',
  move: 'waddle',
  palette: { o: '#3d2c00', b: '#ffd93d', l: '#fff3a6', s: '#f2b705', a: '#ff8c1a', A: '#d96a00' },
  grid: [
    '................',
    '.....oooooo.....',
    '....obbbbbbo....',
    '...obbbbbbbbo...',
    '...oblbbbbbbo...',
    '...obbbbbbbbo...',
    '...obbbbbbbbo...',
    '..oobbbbbbbboo..',
    '.obbbbbbbbbbbbo.',
    'obbsbbbbbbbbsbbo',
    'obbbsbbbbbbsbbbo',
    'obbbbbbbbbbbbbbo',
    '.obbbbbbbbbbbbo.',
    '..ossbbbbbbsso..',
    '...oooooooooo...',
    '................',
  ],
  eyes: [[4, 4], [10, 4]],
  mouth: [6, 6],
  mouthStyle: 'beak',
  cheeks: [[4, 6], [10, 6]],
  hat: [8, 1],
};
