// Ethereal: floats right through walls, so ignored issues hurt its joy 40% less.
export default {
  id: 'ghost',
  trait: 'ethereal',
  home: 'pond',
  modifiers: { issuePenalty: 0.6 },
  food: 'kibble',
  move: 'haunt',
  palette: {
    o: '#1f2a4f', b: '#d6e6fb', l: '#f4f9ff', s: '#a9c2ea', w: '#ffffff', k: '#7f9bd0', f: '#8fe3ff',
    F: '#3d8bff', c: '#e8fbff',
  },
  shinyKeep: ['w', 'f', 'F', 'c'],
  grid: [
    '.....oooooo.....',
    '...oolbkkbboo...',
    '..olbbkwwkbbso..',
    '..okkkwwwwkkko..',
    '..obbbbbbbbbso..',
    '..obbbbbbbbbso..',
    '..obbbbbbbbbso..',
    '.oobbbbbbbbbsoo.',
    'obbbbbbbbbbbbsbo',
    '.ooobbbbbbbbsoo.',
    '...obbbbbbbbbo..',
    '.F.oosbbbbbbbo.o',
    'Ffc.oossbbbbbsoo',
    'FcfF...ooooooo..',
    '.FF.............',
    '................',
  ],
  eyes: [[4, 5], [10, 5]],
  mouth: [6, 8],
  cheeks: [[3, 7], [11, 7]],
  hat: [8, 0],
};
