// Stone Heart: a heart of stone hardly needs food, so hunger builds 60% slower.
export default {
  id: 'golem',
  trait: 'stoneHeart',
  home: 'desert',
  modifiers: { hungerRate: 0.4 },
  food: 'kibble',
  move: 'quake',
  palette: {
    o: '#26242e', b: '#9d9aa8', l: '#c9c6d2', s: '#73707f', f: '#d9d6df', k: '#55525f',
    g: '#7cc04f', G: '#4f8f3a', c: '#4fe8ff', C: '#d2fdff',
  },
  shinyKeep: ['c', 'C'],
  grid: [
    '................',
    '..oooooooooooo..',
    '..oggGggggGggo..',
    '..ogGbgkbgbGgo..',
    '.oolffffffffsoo.',
    'olboffffffffobso',
    'obboffffffffokso',
    'obsoffffffffosso',
    'ooooffffffffoooo',
    'olboffffffffobso',
    'obbobbffffbbobso',
    'obbobbbccbbbobso',
    'ossobbcCCcbbosso',
    '.ooosssccsssooo.',
    '...oooooooooo...',
    '................',
  ],
  eyes: [[4, 6], [10, 6]],
  mouth: [6, 8],
  cheeks: [[4, 8], [10, 8]],
  hat: [8, 1],
};
