// Steel Body: a caped super pup shrugs off red builds. CI can't push its health below 40.
export default {
  id: 'hero',
  trait: 'steel',
  home: 'meadow',
  modifiers: { healthFloor: 40 },
  food: 'kibble',
  palette: {
    o: '#3b2412', b: '#f2c27b', l: '#ffe3b3', s: '#d99a4e', e: '#a0612b', w: '#fff6e6', n: '#2b1a0e',
    r: '#e63946', t: '#2b59c3', y: '#ffd23f',
  },
  shinyKeep: ['r', 't', 'y', 'n', 'w'],
  grid: [
    '................',
    '................',
    '....oooooooo....',
    '..oobllbbbbboo..',
    '.oeobbbbbbbboeo.',
    'oeeobbbbbbbboeeo',
    'oeeobbbbbbbboeeo',
    'oeeobbbbbbbboeeo',
    'oeeobbbbbbbboeeo',
    '.oeobwwnnwwboeo.',
    '.ooobwwwwwwbooo.',
    'rr.obwwwwwwbo.rr',
    'rrr.osbbbbso.rrr',
    'rrr.ottyytto.rrr',
    'rr...oooooo...rr',
    '................',
  ],
  eyes: [[4, 6], [10, 6]],
  mouth: [6, 10],
  cheeks: [[4, 8], [10, 8]],
  hat: [8, 2],
};
