// Stage Smile: always on stage, so its joy never drops below 35.
export default {
  id: 'idol',
  trait: 'stageSmile',
  home: 'meadow',
  modifiers: { joyFloor: 35 },
  food: 'kibble',
  move: 'encore',
  palette: {
    o: '#4a1f3d', b: '#ffb7d0', l: '#ffe3ee', s: '#f08fb3', c: '#fff3e6', p: '#ff8fb8', r: '#ff3d6e',
    R: '#c8204f', y: '#ffd23f', n: '#3b2a4a',
  },
  shinyKeep: ['c', 'r', 'R', 'y', 'n'],
  grid: [
    '.........oo...oo',
    '..ooo....oroooro',
    '.oppyo...orrRrro',
    '.opyyyooooroooro',
    '.nnbyllbboobbboo',
    'obnllbbbbbbbbbso',
    'obnlbbbbbbbbbbso',
    'obnbbbbbbbbbbbso',
    'obnbbbbbbbbbbbso',
    'obnbccccccccbbso',
    'obbnnccccccccbso',
    'obbccccccccccbso',
    '.obbccccccccbso.',
    '..osbccccccbso..',
    '...oooooooooo...',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 10],
  cheeks: [[3, 9], [11, 9]],
  hat: [8, 3],
};
