// Titan: a mini monster grows into a giant, so it levels up 40% faster.
export default {
  id: 'kaiju',
  trait: 'titan',
  home: 'beach',
  modifiers: { xpRate: 1.4 },
  food: 'kibble',
  move: 'roar',
  palette: {
    o: '#163a26', b: '#62c46a', l: '#a6ec9b', s: '#3f9a52', w: '#fff1c9', W: '#ead39a',
    c: '#c4fbff', C: '#5fd8ef',
  },
  shinyKeep: ['w', 'W', 'c', 'C'],
  grid: [
    '......oo........',
    '.....ocCo.......',
    '..oo.ocCo.oo....',
    '.ocCoocCoocCo...',
    '.obbbbbbbbbbo...',
    'oblbbbbbbbbbbo..',
    'olbbbbbbbbbbbo..',
    'obbbbbbbbbbbbo..',
    'obbbbbbbbbbbbo..',
    'obbbbbbbbbbbbo..',
    'obssbbbbbbssboo.',
    'obwsbwwwwbswbbbo',
    'osbbwwwwwwbbssso',
    '.ossbwwwwbsssoo.',
    '..ooooooooooo...',
    '................',
  ],
  eyes: [[3, 7], [9, 7]],
  mouth: [5, 9],
  cheeks: [[1, 9], [10, 9]],
  hat: [7, 4],
};
