// Cucumber Stash: a kappa keeps cucumbers squirrelled away, so hunger builds 30% slower.
export default {
  id: 'kappa',
  trait: 'cucumber',
  home: 'pond',
  modifiers: { hungerRate: 0.7 },
  food: 'kibble',
  move: 'bow',
  palette: {
    o: '#123222', b: '#6fcf6a', l: '#b4ecaa', s: '#45a356', d: '#e6f7ff', D: '#9fd3ee', h: '#2f7d43',
    a: '#ffcf3d', A: '#e39a17', t: '#a8793f', p: '#e4f2a6',
  },
  shinyKeep: ['d', 'D', 'a', 'A', 't', 'p'],
  grid: [
    '................',
    '....oooooooo....',
    '..ooddddddddoo..',
    '.ohhDDddddDDhho.',
    'ohhhhDDDDDDhhhho',
    'ohhhboooooobhhho',
    'ohhbllbbbbbbbhho',
    'ohbbbbbbbbbbbbho',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'otbbbbbbbbbbbbto',
    'otbbbbbbbbbbbbto',
    'ottsbppppppbstto',
    '.ottspppppppsto.',
    '..oooooooooooo..',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  mouthStyle: 'beak',
  cheeks: [[2, 10], [12, 10]],
  hat: [8, 1],
};
