// Nine Tails: a fox spirit grows a tail every century, so it levels up 30% faster.
export default {
  id: 'kitsune',
  trait: 'nineTails',
  home: 'garden',
  modifiers: { xpRate: 1.3 },
  food: 'kibble',
  move: 'tailspin',
  palette: { o: '#4a1f2a', b: '#fff6ea', s: '#f0d2bc', r: '#ea4a2f', y: '#ffc93c' },
  grid: [
    '.........ooo....',
    '........orryo...',
    '.oo.....ooobooo.',
    '.oro....orobbyro',
    '.obro..orboobbyo',
    '.obbboobbbobbbbo',
    'obbbbrrbbbbobbbo',
    'obbbbbbbbbboooo.',
    'obbbbbbbbbbobbyo',
    'obbbbbbbbbbobbro',
    'obbbbbbbbbbobbyo',
    'obbbbbbbbbbosbo.',
    '.obbbbbbbbooo...',
    '..osbbbbso......',
    '...oooooo.......',
    '................',
  ],
  eyes: [[2, 8], [8, 8]],
  mouth: [4, 11],
  cheeks: [[1, 10], [9, 10]],
  hat: [6, 5],
};
