// Nine Tails: a fox spirit grows a tail every century, so it levels up 30% faster.
export default {
  id: 'kitsune',
  trait: 'nineTails',
  home: 'garden',
  modifiers: { xpRate: 1.3 },
  food: 'kibble',
  move: 'tailspin',
  palette: { o: '#4a1f2a', b: '#fff6ea', s: '#f0d2bc', r: '#ea4a2f', y: '#ffc93c' },
  grid: [
    'oo............oo',
    'oro.oo....oo.oro',
    'oyrooro..orooryo',
    'obyoobroorbooybo',
    'obbobbboobbbobbo',
    '.oobbbbbbbbbboo.',
    '..obbbbrrbbbbo..',
    '..obbbbbbbbbbo..',
    '..obbbbbbbbbbo..',
    'oo.obbbbbbbbo.oo',
    'oroobbbbbbbbooro',
    'oyybobbbbbbobyyo',
    'obbbosbbbbsobbbo',
    '.osbsobbbbosbso.',
    '..ooo.oooo.ooo..',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 11],
  cheeks: [[4, 10], [10, 10]],
  hat: [8, 4],
};
