// Gatekeeper: guards the gate, +12 joy while no pull request has gone stale.
export default {
  id: 'knight',
  trait: 'gatekeeper',
  home: 'meadow',
  modifiers: { prJoy: 12 },
  food: 'kibble',
  move: 'guard',
  palette: {
    o: '#1d2333', b: '#3d6fe0', l: '#86a8ff', s: '#2a4fae', f: '#ffdcb8',
    m: '#cfd7e4', M: '#8b97ad', w: '#f6f9fd', r: '#e63946', R: '#a8202c', y: '#ffd23f',
  },
  shinyKeep: ['f', 'm', 'M', 'w', 'y'],
  grid: [
    '........ooo.....',
    '.......orrRo....',
    '......orrRRo....',
    '...ooooMrRoooo..',
    '..owwmmmmmmmmoo.',
    'owmMMffffffMMmMo',
    'owMffffffffffMMo',
    'owMffffffffffMMo',
    'owMffffffffffMMo',
    'owMffffffffffMMo',
    'oooMMffffffMMmMo',
    'oryroMffffMMmMMo',
    'oyyyolbybbybbsoo',
    'oryrolbbyybbso..',
    '.ooo.oooooooo...',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 9],
  cheeks: [[3, 9], [11, 9]],
  hat: [8, 3],
};
