// Old Growth: an old repo is a sacred forest, +2 joy per year of age (up to +12).
export default {
  id: 'kodama',
  trait: 'oldGrowth',
  home: 'jungle',
  modifiers: { ageJoy: 2 },
  food: 'kibble',
  move: 'rattle',
  palette: {
    o: '#24473a', b: '#cdeed8', l: '#effff4', s: '#a3d8b8', g: '#8fd872', G: '#4f9c4c',
  },
  shinyKeep: ['g', 'G'],
  grid: [
    '......gg.GG.....',
    '.......gGG......',
    '.....ooGGoo.....',
    '...oollllbboo...',
    '..olllbbbbbbbo..',
    '.ollbbbbbbbbbso.',
    '.olbbbbbbbbbbso.',
    '.obbbbbbbbbbbso.',
    '.obbbbbbbbbbbso.',
    '.obbbbbbbbbbbso.',
    '..osbbbbbbbbso..',
    '...oooooooooo...',
    '...obsbbbbsbo...',
    '....osbbbbso....',
    '....ooo..ooo....',
    '................',
  ],
  eyes: [[4, 6], [10, 6]],
  mouth: [6, 8],
  cheeks: [[2, 8], [12, 8]],
  hat: [8, 2],
};
