// Fortune: a lucky cat beckons good fortune, +3 joy per 100 stars (up to +20).
export default {
  id: 'maneki',
  trait: 'fortune',
  home: 'garden',
  modifiers: { starJoy: 3 },
  food: 'kibble',
  move: 'beckon',
  palette: {
    o: '#3b2418', b: '#fdf3e7', l: '#ffffff', s: '#ead8c4', O: '#f59a3c', n: '#4a3f45', p: '#ff9eb5',
    r: '#e63946', y: '#ffd23f', Y: '#d9921a',
  },
  shinyKeep: ['r', 'y', 'Y'],
  grid: [
    '.............oo.',
    '..oo......ooolbo',
    '.oOpo....opnobbo',
    '.oOOboooobnnobbo',
    '.oObbbbbbbbbobso',
    '.obbbbbbbbbbobso',
    '.obbbbbbbbbbobso',
    '.obbbbbbbbbbobso',
    '.osbbbbbbbbsobso',
    '..osbbbbbbsoosso',
    '.oorrryyrrrrooo.',
    '.obbbooooobbo...',
    '.obboyyyyobbo...',
    '.osboYyyYobso...',
    '..oooooooooo....',
    '................',
  ],
  eyes: [[3, 5], [9, 5]],
  mouth: [5, 7],
  cheeks: [[2, 7], [10, 7]],
  hat: [7, 3],
};
