// Reactor Core: a green CI powers the reactor, so energy never drops below 40 while CI passes.
export default {
  id: 'mecha',
  trait: 'reactor',
  home: 'desert',
  modifiers: { ciEnergyFloor: 40 },
  food: 'kibble',
  palette: {
    o: '#1b2238', b: '#3d6bff', l: '#8fb0ff', s: '#2a4bc0', f: '#eef3ff',
    y: '#ffd23f', r: '#ff3b3b', e: '#8892a6',
  },
  shinyKeep: ['f', 'y', 'r', 'e'],
  grid: [
    '................',
    '..yy........yy..',
    '...yy......yy...',
    '....yy.rr.yy....',
    '...ooyyrryyoo...',
    '..obbbbbbbbbbo..',
    '.oblbbbbbbbbbbo.',
    'eobffffffffffboe',
    'eobffffffffffboe',
    'eobffffffffffboe',
    'eobffffffffffboe',
    '.obffffffffffbo.',
    '.osbrrrrrrrrbso.',
    '..osbbbbbbbbso..',
    '...oooooooooo...',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[4, 10], [10, 10]],
  hat: [8, 5],
};
