// Treasure: every release fills its chest with loot, +20 joy for two weeks.
export default {
  id: 'mimic',
  trait: 'treasure',
  home: 'reef',
  modifiers: { releaseJoy: 20 },
  food: 'kibble',
  move: 'snap',
  palette: {
    o: '#2b1508', b: '#a3622f', l: '#c98a52', s: '#7a4420', f: '#f0d3a0', y: '#ffd23f', Y: '#c98f12',
    w: '#fffaf0', k: '#3d0f1e', r: '#ff5470', g: '#4fe0d2',
  },
  shinyKeep: ['f', 'y', 'Y', 'w', 'k', 'r', 'g'],
  grid: [
    '................',
    '..oooooooooooo..',
    '.olyllbwgbbbybo.',
    'olbybbbggbbbybso',
    'osyyyyyYYyyyyyso',
    'okwwkwwYYwwkwwko',
    'okkwkrrrrrrkwkko',
    'obbyffffffffybbo',
    'obbyffffffffybbo',
    'obbyffffffffybbo',
    'obbyffffffffybbo',
    'obbyffffffffybbo',
    'osbyffffffffybso',
    'ossyyyyyyyyyyyso',
    '.oooooooooooooo.',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[4, 10], [10, 10]],
  hat: [8, 1],
};
