// Shadow Clone: every day of your commit streak sends out another clone, +4 energy each (up to +24).
export default {
  id: 'ninja',
  trait: 'shadowClone',
  modifiers: { streakEnergy: 4 },
  food: 'kibble',
  palette: {
    o: '#3a1a08', b: '#ff8c42', l: '#ffc48f', s: '#d9661f', w: '#fff4e6', p: '#ff9eb5',
    h: '#1f3a68', m: '#c9d3e0', M: '#7d8aa0',
  },
  shinyKeep: ['w', 'h', 'm', 'M'],
  grid: [
    '................',
    '.oo..........oo.',
    '.opo........opo.',
    '.obpo......opbo.',
    '.obbboooooobbbo.',
    'ohhhhhmmmmhhhhho',
    'ohhhhhmMMmhhhhho',
    'obllbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obwwwbbbbbbwwwbo',
    '.owwwwwwwwwwwwo.',
    '..owwwwwwwwwwo..',
    '...oowwwwwwoo...',
    '.....oooooo.....',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 11],
  cheeks: [[2, 9], [12, 9]],
  hat: [8, 4],
};
