// Multitasker: eight arms love company, every extra active contributor adds energy.
export default {
  id: 'octopus',
  trait: 'multitasker',
  home: 'reef',
  modifiers: { teamEnergy: 6 },
  food: 'kibble',
  move: 'wiggle',
  palette: { o: '#2a1840', b: '#b388ff', l: '#e2d1ff', s: '#8a5cf0' },
  grid: [
    '................',
    '.....oooooo.....',
    '...oobbbbbboo...',
    '..obllbbbbbbbo..',
    '.oblbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.osbbbbbbbbbbso.',
    'obbbbbbbbbbbbbbo',
    'obbobbobbobbobbo',
    '.oo.oo.oo.oo.oo.',
    '................',
    '................',
  ],
  eyes: [[4, 6], [10, 6]],
  mouth: [6, 8],
  cheeks: [[2, 8], [12, 8]],
  hat: [8, 1],
};
