// Iron Club: a little oni with brute strength, its energy never drops below 35.
export default {
  id: 'oni',
  trait: 'ironClub',
  home: 'desert',
  modifiers: { energyFloor: 35 },
  food: 'kibble',
  move: 'stomp',
  palette: {
    o: '#3a0f12', b: '#ee5a4f', l: '#ff9384', s: '#c23b33', h: '#fff2c4', H: '#e2c27a', k: '#2c2240',
    y: '#ffcf3a', w: '#ffffff',
  },
  shinyKeep: ['h', 'H', 'k', 'y', 'w'],
  grid: [
    '...o........o...',
    '..oho......oho..',
    '..ohHo.oo.oHho..',
    '.ohhHookkooHhho.',
    'obbbookkkkoobbbo',
    'obbbbkkkkkkbbbbo',
    'oblbbbkbbkbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'osbbbbbbbbbbbbso',
    'oyoyybbbbbbyoyyo',
    '.oyyoyyoyyoyyoo.',
    '..oooooooooooo..',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 10],
  cheeks: [[2, 9], [12, 9]],
  hat: [8, 4],
};
