// Kung Fu: daily practice makes a master, +3 joy per day of commit streak (up to +18).
export default {
  id: 'panda',
  trait: 'kungfu',
  home: 'jungle',
  modifiers: { streakJoy: 3 },
  food: 'kibble',
  move: 'kick',
  palette: {
    o: '#1d1b24', b: '#f8f4f3', l: '#ffffff', s: '#ddd5d3', k: '#34333f', K: '#62616f',
    r: '#e63946', R: '#a8202c',
  },
  shinyKeep: ['o', 'k', 'K'],
  grid: [
    '..ooo......ooo..',
    '.okkko....okkko.',
    '.okkkooooookkko.',
    '.okkbbbbbbbbkko.',
    '.orrrrrrrrrrrrRr',
    '.olbbbbbbbbbbbRr',
    '.obbbbbbbbbbbbor',
    '.obKbbbbbbbbKbo.',
    '.obKbbbbbbbbKbo.',
    '.obKKbbbbbbKKbo.',
    '.obbbbbbbbbbbbo.',
    '.okkbbbbbbbbkko.',
    'okkkbbbbbbbbkkko',
    'okkksbbbbbbskkko',
    '.oooooooooooooo.',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 10],
  cheeks: [[2, 10], [12, 10]],
  hat: [8, 2],
};
