// Huddle: penguins keep warm together, +5 energy per extra active contributor.
export default {
  id: 'penguin',
  trait: 'huddle',
  home: 'beach',
  modifiers: { teamEnergy: 5 },
  food: 'kibble',
  move: 'slide',
  palette: {
    o: '#0f1828', b: '#34507f', l: '#5f7fb3', s: '#233a60', w: '#f7f9fc', a: '#ffa53d', A: '#e07a12',
    r: '#e8434f', R: '#b02a3a',
  },
  shinyKeep: ['w', 'a', 'A', 'r', 'R'],
  grid: [
    '................',
    '.....oooooo.....',
    '...oollbbbbboo..',
    '..olbbbbbbbbbo..',
    '.olbwwwbbwwwbbo.',
    '.obwwwwwwwwwwbo.',
    '.obwwwwwwwwwwbo.',
    'obbwwwwwwwwwwbbo',
    'obbwwwwwwwwwwbbo',
    'osbbwwwwwwwwbbso',
    'orrrrrrrrrrrrrro',
    'oRRRRRRRRRRRRRRo',
    'osobwwwwwwrRboso',
    '.oobwwwwwwrRbo..',
    '..ooaaaooaaaoo..',
    '................',
  ],
  eyes: [[4, 5], [10, 5]],
  mouth: [6, 7],
  mouthStyle: 'beak',
  cheeks: [[3, 8], [11, 8]],
  hat: [8, 1],
};
