// Rebirth: every release rekindles its flame, +20 energy for two weeks.
export default {
  id: 'phoenix',
  trait: 'rebirth',
  home: 'desert',
  modifiers: { releaseEnergy: 20 },
  food: 'kibble',
  move: 'rise',
  palette: {
    o: '#4a1406', b: '#ff6b2c', l: '#ffa25e', s: '#d8401f', f: '#ffe9a6',
    y: '#ffd23f', r: '#ff3d2e', a: '#f5a524', A: '#c46a00',
  },
  shinyKeep: ['f', 'a', 'A'],
  grid: [
    '.......oo.......',
    '...oo.oyyo.oo...',
    '..oyyooyyooyyo..',
    '..oryooyrooyro..',
    '..obrbbrrbbrbo..',
    '.ollbbbbbbbbbso.',
    '.olbffffffffbso.',
    '.obffffffffffso.',
    'oobffffffffffsoo',
    'oyoffffffffffoyo',
    'oyrobffffffbsryo',
    'orsobffffffbosro',
    '.ooosbbffbbsooo.',
    '...ossbbbbsso...',
    '....oooooooo....',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 9],
  mouthStyle: 'beak',
  cheeks: [[3, 9], [11, 9]],
  hat: [8, 4],
};
