// Crew: a captain loves a full crew, +4 joy per extra active contributor (up to +20).
export default {
  id: 'pirate',
  trait: 'crew',
  home: 'beach',
  modifiers: { teamJoy: 4 },
  food: 'kibble',
  move: 'swing',
  palette: {
    o: '#2a1609', b: '#a86a3d', l: '#cf9463', s: '#7f4a26', c: '#f6e3c3', h: '#2b2733', H: '#4a4458',
    y: '#ffcc33', w: '#ffffff',
  },
  shinyKeep: ['c', 'h', 'H', 'y', 'w'],
  grid: [
    '.....oooooo.....',
    'oo..ohhhhhho..oo',
    'oyo.ohhwwhho.oyo',
    'ohyoohhwwhhooyho',
    'ohhyyhhhhhhyyhho',
    'oohhhyyyyyyhhhoo',
    'oboooooooooooobo',
    'obblbbbbbbbbbbbo',
    'obbbccccccccbbbo',
    'obbccccccccccbbo',
    'obbccccccccccbbo',
    '.obccccccccccbo.',
    '..osbccccccbso..',
    '...oosbbbbsoo...',
    '.....oooooo.....',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[3, 10], [11, 10]],
  hat: [8, 0],
};
