// Static Charge: every commit charges it up, so commits give 50% more energy.
export default {
  id: 'raiju',
  trait: 'staticCharge',
  home: 'desert',
  modifiers: { energyRate: 1.5 },
  food: 'kibble',
  move: 'zap',
  palette: {
    o: '#1b2440', b: '#fff1b8', l: '#fffbe6', s: '#ecd27a', w: '#ffffff', e: '#2f8cff', E: '#a8e8ff',
  },
  shinyKeep: ['w', 'e', 'E'],
  grid: [
    '................',
    '.oo......oo.....',
    '.oEo....oEo.....',
    '.obEo..oEbo.....',
    '.obbboobbbo.....',
    'olbbbbebbbbo...E',
    'obbbbeebbbbo..Ee',
    'obbbbebbbbbo.Ee.',
    'obbbbbbbbbboEe..',
    'obbbbbbbbbboEEEe',
    'obbbwwwwbbbo.Ee.',
    'oeewwwwwweeoEe..',
    '.owwwwwwwwoEe...',
    '..owwwwwwo......',
    '...oooooo.......',
    '................',
  ],
  eyes: [[2, 8], [8, 8]],
  mouth: [4, 10],
  cheeks: [[1, 10], [9, 10]],
  hat: [6, 4],
};
