// Static Charge: every commit charges it up, so commits give 50% more energy.
export default {
  id: 'raiju',
  trait: 'staticCharge',
  home: 'desert',
  modifiers: { energyRate: 1.5 },
  food: 'kibble',
  move: 'zap',
  palette: {
    o: '#1b2440', b: '#fff1b8', l: '#fffbe6', s: '#ecd27a', w: '#ffffff', e: '#2a7fff', E: '#8fd3ff', d: '#1650c8',
  },
  shinyKeep: ['w', 'e', 'E', 'd'],
  grid: [
    '.o........o.....',
    '.oo......oo.....',
    '.oeo....oeo.....',
    '.oeeo..oeeo.....',
    '.obbboobbbo...EE',
    'olbbbbebbbbo.Eed',
    'obbbbeebbbboEed.',
    'obbbbebbbbboeeee',
    'obbbbbbbbbbo.Eed',
    'obbbbbbbbbboEed.',
    'obbbwoowbbboed..',
    'oewwwwwwwweod...',
    '.oewwwwwweo.....',
    '..owwwwwwo......',
    '...oooooo.......',
    '................',
  ],
  eyes: [[2, 8], [8, 8]],
  mouth: [4, 11],
  cheeks: [[1, 10], [9, 10]],
  hat: [6, 4],
};
