// In Bloom: each release brings the blossoms out, +12 joy for two weeks.
export default {
  id: 'sakura',
  trait: 'inBloom',
  home: 'garden',
  modifiers: { releaseJoy: 12 },
  food: 'kibble',
  move: 'bloom',
  palette: {
    o: '#5c2246', b: '#ffb3cf', l: '#ffe2ee', s: '#f28db4', p: '#e9558f', c: '#fff4e8',
  },
  shinyKeep: ['c'],
  grid: [
    '.....oo..oo.....',
    '....obboobbo....',
    '.oooolbbbbboooo.',
    'obbbobbbbbbobbbo',
    '.olbbopccpobbbo.',
    'olbbbpcccccpbbbo',
    '.obbpcccccccpbo.',
    '..occcccccccco..',
    '..occcccccccco..',
    '..occcccccccco..',
    '..occcccccccco..',
    '.obpccccccccpbo.',
    'obbbbpccccpbbbbo',
    'obbobboooobbobbo',
    '.oo.oo....oo.oo.',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[3, 10], [11, 10]],
  hat: [8, 1],
};
