// In Bloom: each release brings the blossoms out, +12 joy for two weeks.
export default {
  id: 'sakura',
  trait: 'inBloom',
  home: 'garden',
  modifiers: { releaseJoy: 12 },
  food: 'kibble',
  move: 'bloom',
  palette: {
    o: '#5c2246', b: '#ffb3cf', l: '#ffe2ee', s: '#f28db4', p: '#e9558f', c: '#fff4e8', g: '#c4f0c8', G: '#86d69a', y: '#ffd76a',
  },
  shinyKeep: ['c', 'g', 'G', 'y'],
  grid: [
    '.oo...o..o...oo.',
    'ogGo.oloolo.oGgo',
    '.oGGoobbbbbooGGo',
    '.oooobssssboooo.',
    'olbbpssppsspbblo',
    'olbbscyppycsbblo',
    '.obscccyycccsbo.',
    'obbsccccccccsbbo',
    'obbsccccccccsbbo',
    '.obpccccccccpbo.',
    '..osccccccccso..',
    '.obbsccccccsbbo.',
    '.obbbsccccsbbbo.',
    '.olbbboooobbblo.',
    '..ooooo..ooooo..',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[4, 10], [10, 10]],
  hat: [8, 1],
};
