// Bushido: a ronin shiba trains every day, +12 energy on any day with a commit.
export default {
  id: 'samurai',
  trait: 'bushido',
  home: 'meadow',
  modifiers: { dailyEnergy: 12 },
  food: 'kibble',
  move: 'slash',
  palette: {
    o: '#2e1a0c', b: '#e9a253', l: '#fbd08f', s: '#c97d33', w: '#fff1db', k: '#2a2433', t: '#ffffff',
    h: '#34418a', H: '#252f66', y: '#ffcc3d', c: '#5b4a9a',
  },
  shinyKeep: ['w', 'k', 't', 'h', 'H', 'y', 'c'],
  grid: [
    '.......oo.......',
    '.oo...okko...oo.',
    '.owo..okko..owo.',
    '.obwo.otto.owbo.',
    '.obbboooooobbbo.',
    'obbbbwbbbbwbbbbo',
    'oblbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obwwwbbbbbbwwwbo',
    '.owwwwwwwwwwwwo.',
    '..owwwwwwwwwwyoo',
    '.ohhhwwwwwwhhycy',
    '.oHhhhhwwhhhHyoo',
    '..oooooooooooo..',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 10],
  cheeks: [[2, 9], [12, 9]],
  hat: [8, 4],
};
