// Bushido: a ronin shiba trains every day, +12 energy on any day with a commit.
export default {
  id: 'samurai',
  trait: 'bushido',
  home: 'meadow',
  modifiers: { dailyEnergy: 12 },
  food: 'kibble',
  move: 'slash',
  palette: {
    o: '#2e1a0c', b: '#e8964a', l: '#f8c48a', s: '#c4732e', w: '#fff1db', k: '#2a2433',
    h: '#34418a', H: '#222b5c', y: '#ffcc3d',
  },
  shinyKeep: ['w', 'k', 'h', 'H', 'y'],
  grid: [
    '................',
    '.oo...oooo...oo.',
    '.owo.okkkko.owo.',
    '.obwo.okko.owbo.',
    '.obbboooooobbbo.',
    'obbbbbbbbbbbbbbo',
    'obllwwbbbbwwbbbo',
    'obbbbbbbbbbbbbbo',
    'obbbbbbbbbbbbbbo',
    'obwwwbbbbbbwwwbo',
    '.owwwwwwwwwwwwo.',
    '.owwwwwwwwwwwwoy',
    '.ohhhwwwwwwhhhyk',
    '..oHhhhwwhhhhyk.',
    '...oooooooooo...',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 10],
  cheeks: [[2, 9], [12, 9]],
  hat: [8, 4],
};
