// Never Stop: a shark never stops swimming, +3 energy per day of commit streak (up to +18).
export default {
  id: 'shark',
  trait: 'neverStop',
  home: 'reef',
  modifiers: { streakEnergy: 3 },
  food: 'kibble',
  move: 'chomp',
  palette: {
    o: '#14273d', b: '#6f9fcb', l: '#a9cbe8', s: '#4f7ba6', w: '#f4f8fc', g: '#3b6389',
  },
  shinyKeep: ['w'],
  grid: [
    '.........o......',
    '........obo.....',
    '.......olbo.....',
    '......olbbo.....',
    '....oolbbboo....',
    '...obllbbbbbo.oo',
    '..obllbbbbbbbobo',
    '.obbbbbbbbbbbsbo',
    '.obbbbbbbbbbbso.',
    '.obgbbbbbbbbgbo.',
    '.obgwwwwwwwwgbo.',
    'oobwwwwwwwwwwboo',
    'osobwwwwwwwwbos.',
    '.o.osswwwwssooo.',
    '...oooooooooo...',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 10],
  cheeks: [[3, 9], [11, 9]],
  hat: [8, 4],
};
