// Never Stop: a shark never stops swimming, +3 energy per day of commit streak (up to +18).
export default {
  id: 'shark',
  trait: 'neverStop',
  home: 'reef',
  modifiers: { streakEnergy: 3 },
  food: 'kibble',
  move: 'chomp',
  palette: {
    o: '#14273d', b: '#6f9fcb', l: '#a9cbe8', s: '#4f7ba6', w: '#f4f8fc', g: '#3b6389',
  },
  shinyKeep: ['w'],
  grid: [
    '................',
    '.........oo.....',
    '........olo..o..',
    '.......olso.oso.',
    '......olbssoosoo',
    '...oolbbbbsossso',
    '..olbbbbbbbbsoo.',
    '.olbbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    'oobbbbbbbbbbbsoo',
    'osgbbwwwwwwbgsso',
    'osgbwwwwwwwwgsso',
    '.oobwwwwwwwwboo.',
    '..osswwwwwwsso..',
    '...oooooooooo...',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 11],
  cheeks: [[3, 10], [11, 10]],
  hat: [8, 5],
};
