// Patient: snakes eat rarely, so hunger builds 40% slower.
export default {
  id: 'snake',
  trait: 'patient',
  home: 'jungle',
  modifiers: { hungerRate: 0.6 },
  food: 'kibble',
  move: 'slither',
  palette: { o: '#16351f', b: '#6fcf6f', l: '#b6f0a8', s: '#44a454', d: '#2f7a3d' },
  grid: [
    '................',
    '.....oooooo.....',
    '....ollbbbbo....',
    '...obbbbbbbbo...',
    '...obbbbbbbbo...',
    '...obbbbbbbbo...',
    '....obbbbbbo....',
    '.....obbbbo.....',
    '...ooobbbbooo...',
    '..obbdbbbbdbbo..',
    '..osssssssssso..',
    '.obbbdbbbbdbbbo.',
    '.osssssssssssso.',
    'obbdbbbdbbbdbbbo',
    'oooooooooooooooo',
    '................',
  ],
  eyes: [[4, 3], [10, 3]],
  mouth: [6, 5],
  cheeks: [[4, 5], [10, 5]],
  hat: [8, 1],
};
