// Matsuri: festival spirit, +5 joy for every extra active contributor (up to +20).
export default {
  id: 'tanuki',
  trait: 'matsuri',
  home: 'jungle',
  modifiers: { teamJoy: 5 },
  food: 'kibble',
  move: 'poof',
  palette: {
    o: '#2e1d12', b: '#b08257', l: '#d1a678', s: '#8a6140', m: '#5c3d27', r: '#efdcc0', w: '#f8ecd6',
    g: '#7ed957', G: '#2f8f3a',
  },
  shinyKeep: ['g', 'G'],
  grid: [
    '.........oo.....',
    '.......oogGo....',
    '..oo..ogGggooo..',
    '.omso.oGggoosmo.',
    '.ombbooGooobbmo.',
    'obbbbbbbbbbbbbbo',
    'oblbbbbbbbbbbbbo',
    'obbmrrmbbmrrmbbo',
    'obmrrrrbbrrrrmbo',
    'ommrrrrbbrrrrmmo',
    'obmmrrmbbmrrmmbo',
    'obbbmwwwwwwmbbbo',
    '.obbwwwwwwwwbbo.',
    '..osbwwwwwwbso..',
    '...oooooooooo...',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 11],
  cheeks: [[2, 11], [12, 11]],
  hat: [8, 4],
};
