// Gust: a crow tengu rides the wind, so every commit gives 25% more energy.
export default {
  id: 'tengu',
  trait: 'gust',
  home: 'jungle',
  modifiers: { energyRate: 1.25 },
  food: 'kibble',
  move: 'gale',
  palette: {
    o: '#0e0c16', b: '#34304d', l: '#5a5580', s: '#211e33', f: '#e6e4ef', k: '#121019', r: '#e63946',
    w: '#ffffff', a: '#ffb627', A: '#e07a10',
  },
  shinyKeep: ['f', 'k', 'r', 'w', 'a', 'A'],
  grid: [
    '................',
    '......oooo......',
    '.....okkkko.....',
    '...oookkkkooo...',
    '..obbrrrrrrbbo..',
    '.obbbbbbbbbbrbo.',
    'oblffffbbffffrbo',
    'obffffffffffffbo',
    'obffffffffffffbo',
    'obbffffffffffbbo',
    'obbbffffffffbbbo',
    'osbbbbbbbbbbbbso',
    'oobbwwbbbbwwbboo',
    '.osbwwbbbbwwbso.',
    '..oooooooooooo..',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 9],
  mouthStyle: 'beak',
  cheeks: [[3, 9], [11, 9]],
  hat: [8, 3],
};
