// Gust: a crow tengu rides the wind, so every commit gives 25% more energy.
export default {
  id: 'tengu',
  trait: 'gust',
  home: 'jungle',
  modifiers: { energyRate: 1.25 },
  food: 'kibble',
  move: 'gale',
  palette: {
    o: '#0e0c16', b: '#36324f', l: '#6b6699', s: '#221f35', f: '#dddbe9', k: '#121019', r: '#e63946',
    w: '#ffffff', a: '#ffb627', A: '#e07a10',
  },
  shinyKeep: ['f', 'k', 'r', 'w', 'a', 'A'],
  grid: [
    '.......oo.......',
    '......okko......',
    '.....okllko.....',
    '..oooorrrroooo..',
    '.obbbrbbbbrbbbo.',
    'oblbbbbbbbbbbbbo',
    'obbfffbbbbfffbbo',
    'obffffffffffffbo',
    'obffffffffffffbo',
    'obbbffffffffbbbo',
    'oobbbbbbbbbbbboo',
    'lsobbwwbbwwbbosl',
    'lssobwfbbwfbossl',
    '.lsoobbbbbboosl.',
    '..ll.oooooo.ll..',
    '................',
  ],
  eyes: [[4, 7], [10, 7]],
  mouth: [6, 9],
  mouthStyle: 'beak',
  cheeks: [[4, 9], [10, 9]],
  hat: [8, 3],
};
