// Undying: a little vampire always gets back up, so failing CI hurts it only half as much.
export default {
  id: 'vampire',
  trait: 'undying',
  home: 'garden',
  modifiers: { ciPenalty: 0.5 },
  food: 'kibble',
  move: 'swoop',
  palette: {
    o: '#140d1c', b: '#e4dcef', l: '#f8f5fc', s: '#c2b5d6', h: '#32284a', H: '#6b5c94',
    c: '#2e2340', r: '#e0304a', R: '#a31c37', y: '#ffd23f',
  },
  shinyKeep: ['r', 'R', 'y'],
  grid: [
    '................',
    '.....oooooo.....',
    '...ooHHhhhhoo...',
    '..ohHhhhhhhhho..',
    'o.ohhhhhhhhhho.o',
    'orohhlbhhbbhhoro',
    'crohbbbhhbbbhorc',
    'crohbbbbbbbbhorc',
    'crobbbbbbbbbborc',
    'crobbbbbbbbbborc',
    'crobbbbbbbbbborc',
    'crcobbbbbbbbocrc',
    'crccosbbbbsoccrc',
    'cRcccoyrryocccRc',
    'c.c.oooooooo.c.c',
    '................',
  ],
  eyes: [[4, 8], [10, 8]],
  mouth: [6, 10],
  cheeks: [[3, 10], [11, 10]],
  hat: [8, 1],
};
