// Grimoire: a tidy repo is a good spellbook, +12 joy while the community profile is 80% or more.
export default {
  id: 'witch',
  trait: 'grimoire',
  home: 'garden',
  modifiers: { tidyJoy: 12 },
  food: 'kibble',
  move: 'broom',
  palette: {
    o: '#2a1a3d', b: '#8fe3c0', l: '#d4fbe9', s: '#5cc29d',
    h: '#8a5ad6', H: '#5e36a8', y: '#ffd23f', n: '#9a6232', k: '#f2c46b',
  },
  shinyKeep: ['h', 'H', 'y', 'n', 'k'],
  grid: [
    '......ooooooo...',
    '.....ohhhhhhhoo.',
    '.....ohhhooohhho',
    '....ohhhhho.ooo.',
    '.oooHHHyyHHHooo.',
    'ohhhhhhhhhhhhhho',
    '.ooHHHHHHHHHHoo.',
    '..obllbbbbbbbo..',
    '.oblbbbbbbbbbbon',
    '.obbbbbbbbbbbbon',
    '.obbbbbbbbbbbbno',
    '.obbbbbbbbbbbbno',
    '.osbbbbbbbbbbkkk',
    '..osbbbbbbbbkkkk',
    '...ooooooooookkk',
    '................',
  ],
  eyes: [[4, 9], [10, 9]],
  mouth: [6, 11],
  cheeks: [[3, 11], [11, 11]],
  hat: [8, 0],
};
