// Grimoire: a tidy repo is a good spellbook, +12 joy while the community profile is 80% or more.
export default {
  id: 'witch',
  trait: 'grimoire',
  home: 'garden',
  modifiers: { tidyJoy: 12 },
  food: 'kibble',
  move: 'broom',
  palette: {
    o: '#2a1a3d', b: '#8fe3c0', l: '#d4fbe9', s: '#5cc29d',
    h: '#8a5ad6', H: '#5e36a8', j: '#b48cf0', y: '#ffd23f', n: '#9a6232', k: '#f2c46b',
  },
  shinyKeep: ['o', 'h', 'H', 'j', 'y', 'n', 'k'],
  grid: [
    'n......oooo.....',
    '.n....ohhhhooo..',
    '..n...ojhhhhhho.',
    '...n.ojhhhoooHo.',
    '....ojhhhhHo.o..',
    '.oooHHHyyHHHooo.',
    'ohhhhhhhhhhhhhho',
    'oobllbbbbbbbbooo',
    '.oblbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.obbbbbbbbbbbbo.',
    '.obbbbbbbbbbbHHo',
    '.osbbbbbbbbbokko',
    '..osbbbbbbbokkko',
    '...ooooooooknknk',
    '................',
  ],
  eyes: [[4, 9], [10, 9]],
  mouth: [6, 11],
  cheeks: [[2, 10], [12, 10]],
  hat: [8, 0],
};
